/**
 * Italian keyword dictionaries for section identification.
 * Comprehensive coverage of real estate appraisal (perizia) terminology.
 * Includes accent-normalized variants, abbreviations, alternative phrasings.
 */

export const KEYWORDS = {
  antecedentActs: [
    // ── Core chapter titles ──
    'atti antecedenti',
    'atto antecedente',
    'atti precedenti',
    'atti anteriori',
    'atti pregressi',
    'provenienza',
    'provenienza del bene',
    "provenienza dell'immobile",
    'provenienza dell immobile',
    'titoli di provenienza',
    'titolo di provenienza',
    'titolo di acquisto',
    'titoli di acquisto',
    // ── Formalità pregiudizievoli ──
    'formalità',
    'formalita',
    'formalita pregiudizievoli',
    'formalità pregiudizievoli',
    'atti pregiudizievoli',
    'iscrizioni',
    'iscrizione',
    'trascrizioni',
    'trascrizione',
    'pregiudizievoli',
    'pregiudizievole',
    // ── Ipoteche / vincoli ──
    'vincoli',
    'vincolo',
    'servitù',
    'servitu',
    'servitù prediali',
    'servitu prediali',
    'ipoteca',
    'ipoteche',
    'ipoteca volontaria',
    'ipoteca giudiziale',
    'ipoteca legale',
    'ipoteca esattoriale',
    'pignoramento',
    'pignoramenti',
    'sequestro',
    'sequestri',
    // ── Atti di trasferimento ──
    'nota di trascrizione',
    'nota di iscrizione',
    'note di trascrizione',
    'note di iscrizione',
    'registro immobiliare',
    'conservatoria dei registri',
    'conservatoria',
    'agenzia delle entrate',
    'compravendita',
    'contratto di compravendita',
    'donazione',
    'successione',
    'eredità',
    'eredita',
    'accettazione eredità',
    'accettazione di eredita',
    'testamento',
    'eredi',
    'erede',
    'divisione',
    'divisione ereditaria',
    'permuta',
    'decreto di trasferimento',
    'decreto trasferimento',
    'atto notarile',
    'atto pubblico',
    'repertorio',
    'raccolta',
    'rogito',
    'notaio',
    'rep. n.',
    'racc. n.',
    'rep n',
    'racc n',
    // ── Stato risultante ──
    'trascritto',
    'iscritto',
    'annotato',
    'cancellazione',
    'cancellazione ipoteca',
    'decreto ingiuntivo',
    'sentenza',
    'privilegio',
    'privilegio speciale',
    'convenzione matrimoniale',
    'separazione dei beni',
    'regime patrimoniale',
    // ── Visure ──
    'visure catastali',
    'visura ipotecaria',
    'visure ipotecarie',
    'visura catastale',
    'storico catastale',
    'storia dell immobile',
    "storia dell'immobile",
    'planimetria catastale',
    // ── Mutui ──
    'mutuo ipotecario',
    'finanziamento ipotecario',
    'surroga',
    'estinzione mutuo',
    'accollo mutuo',
    // ── Sentenze / procedure ──
    'procedura esecutiva',
    'procedura esecutiva immobiliare',
    'esecuzione immobiliare',
    'esproprio',
    'espropriazione',
    'espropriazione forzata',
    'giudice dell esecuzione',
    "giudice dell'esecuzione",
  ],

  legalCosts: [
    // ── Core chapter titles ──
    'oneri',
    'oneri a carico',
    'oneri fiscali',
    'oneri condominiali',
    "oneri a carico dell'aggiudicatario",
    'oneri a carico dell aggiudicatario',
    'spese',
    'spese a carico',
    'spese condominiali',
    'spese arretrate',
    'spese ordinarie',
    'spese straordinarie',
    'costi di legge',
    'costi a carico',
    'costi e spese',
    // ── Arretrati condominiali ──
    'arretrati',
    'arretrato',
    'quote condominiali',
    'rate condominiali',
    'debiti condominiali',
    'morosità',
    'morosita',
    'insoluto',
    'insoluti',
    'delibere condominiali',
    'delibera condominiale',
    'fondo cassa',
    'fondo condominiale',
    'gestione condominiale',
    'condominio',
    'amministratore di condominio',
    'registro di condominio',
    'bilancio condominiale',
    'consuntivo',
    'preventivo',
    'rendiconto',
    'riscaldamento centralizzato',
    // ── Ultimi due anni ──
    'ultimi due anni',
    'ultimi 2 anni',
    'biennio',
    'due annualità',
    'due annualita',
    'ultimo biennio',
    'ultime due annualità',
    'ultime due annualita',
    'negli ultimi due anni',
    'nei due anni precedenti',
    // ── Tributi ──
    'tributi',
    'tasse',
    'imposte',
    'imu',
    'tari',
    'tasi',
    'imposta municipale',
    'imposta municipale propria',
    'imu arretrata',
    'canone idrometrico',
    'oneri tributari',
    // ── Occupazione / locazione ──
    'occupazione',
    'occupante',
    'affitto',
    'canone',
    'locazione',
    'locatario',
    'conduttore',
    'spese di liberazione',
    'liberazione',
    'rilascio',
    'occupazione abusiva',
    // ── Aggiudicatario ──
    'a carico dell aggiudicatario',
    "a carico dell'aggiudicatario",
    'aggiudicatario',
    'aggiudicazione',
    'accollo',
    'soggetto ad accollo',
    // ── Regolarizzazione ──
    'regolarizzazione',
    'sanatoria',
    'contributo',
    'contributo di costruzione',
    'onere di urbanizzazione',
    'oneri di urbanizzazione',
    // ── Mutuo/Finanziamento ──
    'mutuo',
    'mutuo ipotecario',
    'finanziamento',
    'leasing immobiliare',
    'canone mutuo',
    'rate mutuo',
    // ── Passività ──
    'passività',
    'passivo',
    'vincolo di pagamento',
    'debiti',
    'bollette',
    'utenze',
    // ── Spese generali ──
    'spese di procedura',
    'spese legali',
    'diritti di cancelleria',
    'spese di vendita',
    'costi di vendita',
  ],

  irregularities: [
    // ── Core chapter titles ──
    'difformità',
    'difformita',
    'difformità urbanistica',
    'difformità catastale',
    'difformità edilizia',
    'difformità rispetto al catasto',
    'difformita rispetto al catasto',
    'difformità planimetrica',
    // ── Non conformità ──
    'non conforme',
    'non conformità',
    'non conformita',
    'irregolarità',
    'irregolarita',
    'non regolare',
    'irregolare',
    'non corrispondente',
    'non coincidente',
    'discordanza',
    'discordanze',
    // ── Abusi edilizi ──
    'abuso',
    'abusi',
    'abuso edilizio',
    'abusi edilizi',
    'opere abusive',
    'opera abusiva',
    'costruzione abusiva',
    'costruzioni abusive',
    'ampliamento abusivo',
    'sopraelevazione abusiva',
    // ── Sanatoria / condono ──
    'sanatoria',
    'condono',
    'condono edilizio',
    'condono ottenuto',
    'sanatoria edilizia',
    'sanatoria ottenuta',
    'istanza di condono',
    'domanda di condono',
    'condono pendente',
    'condono non ottenuto',
    // ── Stato legittimo ──
    'stato legittimo',
    'stato legittimato',
    'legittimita',
    'legittimità',
    'titolo legittimante',
    'regolarità',
    'regolarita',
    // ── Conformità ──
    'conformità',
    'conformita',
    'conformità urbanistica',
    'conformita urbanistica',
    'conformità catastale',
    'conformita catastale',
    'conformità edilizia',
    'conformita edilizia',
    // ── Titoli abilitativi ──
    'titolo abilitativo',
    'titoli abilitativi',
    'permesso di costruire',
    'pdC',
    'licenza edilizia',
    'concessione edilizia',
    'concessione a costruire',
    'autorizzazione a costruire',
    'scia',
    'dia',
    'cila',
    'cil',
    'autorizzazione paesaggistica',
    'variante',
    'variante in corso d opera',
    "variante in corso d'opera",
    'variazione catastale',
    // ── Agibilità ──
    'agibilità',
    'agibilita',
    'abitabilità',
    'abitabilita',
    'certificato di agibilità',
    'certificato di abitabilità',
    'dichiarazione di agibilità',
    'dichiarazione di conformità',
    'certificato di collaudo',
    'collaudo',
    // ── Catasto ──
    'planimetria',
    'planimetria catastale',
    'visura catastale',
    'categoria catastale',
    'rendita catastale',
    'subalterno',
    'foglio',
    'mappale',
    'particella',
    'superficie catastale',
    // ── Impianti ──
    'impianti',
    'impiantistica',
    'certificazione impianti',
    'dichiarazione di conformità degli impianti',
    'impianto elettrico',
    'impianto idraulico',
    'impianto termico',
    // ── Vincoli ──
    'vincolo ambientale',
    'vincolo paesaggistico',
    'vincolo idrogeologico',
    'vincolo sismico',
    'area vincolata',
    'piano paesaggistico',
    'soprintendenza',
    'nulla osta',
    'parco nazionale',
    'area protetta',
    'bene culturale',
    'zona rossa',
    // ── Destinazione d'uso ──
    'destinazione d uso',
    "destinazione d'uso",
    'cambio di destinazione',
    'cambio destinazione d uso',
    'mutamento di destinazione',
    // ── Stato dei luoghi ──
    'stato dei luoghi',
    'stato attuale',
    'stato di fatto',
    'superficie lorda',
    'superficie commerciale',
    'ristrutturazione',
    'ampliamento',
    'sopraelevazione',
    'demolizione',
    'recupero',
    // ── Relazione tecnica ──
    'relazione tecnica',
    'perizia tecnica',
    'relazione di conformità',
    'certificato di conformità',
    'attestazione',
    'attestato',
  ],

  expertValue: [
    // ── Core chapter titles ──
    'valore di stima',
    'valore di mercato',
    'determinazione del valore',
    'determinazione del valore di mercato',
    'valore di perizia',
    'valore stimato',
    'valore stimato dell immobile',
    "valore stimato dell'immobile",
    'valore commerciale',
    'valore venale',
    'valore venale di mercato',
    'valore complessivo',
    'valore totale',
    'più probabile valore',
    'piu probabile valore',
    "più probabile valore di mercato",
    // ── Base d'asta ──
    "base d'asta",
    'base d asta',
    'prezzo base',
    'prezzo base d asta',
    "prezzo base d'asta",
    'valore base',
    'lotto base',
    // ── Stima ──
    'stima',
    'stimasi',
    'si stima',
    'viene stimato',
    'viene stimata',
    'è stimato',
    'e stimato',
    'è stimata',
    'e stimata',
    'stima in',
    'stimato in',
    'valore di stima pari',
    'valore dell immobile',
    "valore dell'immobile",
    'valore immobile',
    'valore immobiliare',
    // ── Valutazione ──
    'valutazione',
    'valutazione dell immobile',
    "valutazione dell'immobile",
    'perizia di stima',
    'relazione di stima',
    'valore peritale',
    'perizia di valutazione',
    // ── CTU / Perito ──
    'CTU',
    'C.T.U.',
    'consulente tecnico d ufficio',
    "consulente tecnico d'ufficio",
    'consulente tecnico',
    'perito',
    'perito estimatore',
    'valutatore',
    // ── Prezzo ──
    'prezzo di mercato',
    'prezzo corrente',
    'prezzo di vendita',
    'prezzo stimato',
    'ricavo probabile',
    'prezzo più probabile',
    'piu probabile prezzo',
    'prezzo finale',
    'valore finale',
    'valore di liquidazione',
    'valore cauzionale',
    // ── OMI ──
    'quotazioni omi',
    'osservatorio del mercato immobiliare',
    'omi',
    'o.m.i.',
    'valore unitario',
    'prezzo unitario',
    'valore al mq',
    'prezzo al mq',
    'al metro quadro',
    'al metro quadrato',
    'euro/mq',
    '€/mq',
    // ── Importo complessivo ──
    'importo complessivo',
    'importo totale',
    'totale stimato',
    'totale dell immobile',
    "totale dell'immobile",
    // ── Calcolo ──
    'stima del valore venale',
    'calcolo del valore',
    'metodo di stima',
    'metodo comparativo',
    'metodo del costo',
    'metodo reddituale',
    'capitalizzazione del reddito',
    // ── Contesto temporale ──
    'alla data della perizia',
    'alla data di stima',
    'alla data odierna',
    'alla data del',
    'valore attuale',
    'valore corrente',
  ],
} as const;

export type FieldType = keyof typeof KEYWORDS;
export const FIELD_TYPES: FieldType[] = Object.keys(KEYWORDS) as FieldType[];

/**
 * Keywords that indicate "ultimi 2 anni" context for legal costs.
 */
export const ULTIMI_DUE_ANNI_PATTERNS = [
  'ultimi due anni',
  'ultimi 2 anni',
  'biennio',
  'due annualità',
  'due annualita',
  'ultimo biennio',
  'ultime due annualità',
  'ultime due annualita',
];
